---

- name: Set docroot permissions
  file: dest='{{ drupal_absolute_docroot }}' mode=750 state=directory owner=nginx group=nginx recurse=yes

- name: Change sites/default/files permissions 
  file: path="{{ drupal_absolute_docroot }}/sites/default/files" state=directory follow=yes owner=nginx group=nginx recurse=yes mode=770

- name: Change settings.php permissions
  file: path="{{ drupal_absolute_docroot }}/sites/default/settings.php" state=file owner=nginx group=nginx mode=750

     
