---

- name: start php56-fpm
  service: name=php-fpm-5.6 enabled=yes state=started

- name: restart php56-fpm
  service: name=php-fpm-5.6 enabled=yes state=restarted

- include: ../nginx/handlers/main.yml
